with open('README.md', 'w') as f:
    f.write('# SovereignFlow Gateway\n\n')
    f.write('PATENT PENDING -- USPTO Application 64/038,618 Filed April 14, 2026.\n\n')
    f.write('The S3-compatible software layer for biological data storage.\n')
    f.write('Written in Rust. Triple-layer ECC. Production speed. Hardware agnostic.\n\n')
    f.write('## Benchmarks\n\n')
    f.write('Peak encode 4 cores: 1251 MB/s (10.0 Gb/s)\n')
    f.write('Peak decode: 2803 MB/s (22.4 Gb/s)\n')
    f.write('Code rate: 0.513 to 1.087 bits/base (hardware-tunable)\n')
    f.write('Deletion tolerance: 40%\n')
    f.write('Recovery: 100% byte-perfect at 1GB scale\n')
    f.write('Index: 1TB+ RocksDB\n\n')
    f.write('## Build\n\ncargo build --release\n\n')
    f.write('Patent pending USPTO 64/038,618. Built in Rust.\n')
print('Done')
